runtime: php
env: flex

runtime_config:
    document_root: public


skip_files:
    .env

env_variables:
    APP_LOG: errorlog
    APP_KEY: base64:dVPw9uhOxffmZcxCjdHh4glFqBfPICwhHbbY1VoWHBg=
    APP_TIMEZONE: GMT+1
    APP_DEBUG: true

    CACHE_DRIVER: database
    SESSION_DRIVER: database

    DB_CONNECTION: mysql
    DB_HOST: localhost
    DB_PORT: 3306
    DB_DATABASE: Online
    DB_USERNAME: Mike
    DB_PASSWORD: ekottomike
    DB_SOCKET: "/cloudsql/btech-seas-319617:us-central1:db-instance"

beta_settings:
    cloud_sql_instances: "btech-seas-319617:us-central1:db-instance"
