runtime: php
env: flex

runtime_config:
    document_root: ./resources/views


skip_files:
    .env

env_variables:
    APP_LOG: daily
    APP_KEY: base64:dVPw9uhOxffmZcxCjdHh4glFqBfPICwhHbbY1VoWHBg=
    APP_TIMEZONE: GMT+1

    CACHE_DRIVER: file
    SESSION_DRIVER: file

    DB_CONNECTION: mysql
    DB_HOST: localhost
    DB_DATABASE: db-instance
    DB_USERNAME: Mike
    DB_PASSWORD: ekottomike
    DB_SOCKET: /cloudsql/btech-seas-319617:us-central1:db-instance

GOOGLE_VISION_PROJECT_ID: btech-seas-319617

beta_settings:
    cloud_sql_instances:"btech-seas-319617:us-central1:db-instance"
